sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t abudesai/docker-react -f Dockerfile.dev . 

script: 
    - docker run -e CI=true abudesai/docker-react npm run test -- --coverage